# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-25 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_file', models.FileField(blank=True, upload_to='upload_image')),
            ],
        ),
    ]
