# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_conv_app', '0002_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('improve_layout', models.TextField(blank=True, default='')),
                ('improve_feature', models.TextField(blank=True, default='')),
                ('improve_lag', models.TextField(blank=True, default='')),
                ('improve_image', models.TextField(blank=True, default='')),
                ('improve_other', models.TextField(blank=True, default='')),
                ('follow_up', models.BooleanField(default=False)),
                ('email_feedback', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
