# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_conv_app', '0003_auto_20180820_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_liker', models.ManyToManyField(related_name='liked_comments', to='unit_conv_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_liker', models.ManyToManyField(related_name='liked_posts', to='unit_conv_app.User')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='unit_conv_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, default='')),
                ('response_category', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(max_length=255, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email_feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='improve_feature',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='improve_image',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='improve_lag',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='improve_layout',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='improve_other',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='response',
            name='survey_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_key', to='unit_conv_app.Feedback'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_comments', to='unit_conv_app.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='unit_conv_app.User'),
        ),
    ]
