# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-22 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_conv_app', '0004_auto_20180821_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='survey_key',
        ),
        migrations.AddField(
            model_name='feedback',
            name='conversion_response',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feature_response',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='layout_response',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='other_response',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='speed_response',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
