# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_conv_app', '0006_auto_20180822_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='conversion',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='conversion_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feature',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feature_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='layout',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='layout_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='other',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='other_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='speed',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='speed_response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
