# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-22 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_conv_app', '0007_auto_20180822_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
