# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-27 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_conv_app', '0010_auto_20180826_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status_comment',
            field=models.TextField(default=''),
        ),
    ]
