# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_conv_app', '0011_auto_20180827_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='unit_conv_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='upload',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
