# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-31 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_conv_app', '0016_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='category',
            new_name='response_category',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response',
            new_name='response_text',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='conversion',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='conversion_response',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='feature_response',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='layout_response',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='other',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='other_response',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='speed_response',
        ),
        migrations.RemoveField(
            model_name='response',
            name='responder',
        ),
        migrations.AddField(
            model_name='response',
            name='respond_feedback',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='unit_conv_app.Feedback'),
            preserve_default=False,
        ),
    ]
